#define CHDR_VERSION         "0.1.0-alpha"
#define CHDR_VERSION_MAJOR    0
#define CHDR_VERSION_MINOR    1
#define CHDR_VERSION_PATCH    0
#define CHDR_VERSION_TWEAK    
#define CHDR_VERSION_METADATA @CHDR_VERSION_METADATA
